//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontDataEntities : DbContext
    {
        public StoreFrontDataEntities()
            : base("name=StoreFrontDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory1> C__MigrationHistory1 { get; set; }
        public virtual DbSet<Address12> Address12 { get; set; }
        public virtual DbSet<blog1> blog1 { get; set; }
        public virtual DbSet<CustomerBaseViewModel1> CustomerBaseViewModel1 { get; set; }
        public virtual DbSet<OrderProduct1> OrderProduct1 { get; set; }
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<ShoppingCart1> ShoppingCart1 { get; set; }
        public virtual DbSet<ShoppingCartProduct1> ShoppingCartProduct1 { get; set; }
        public virtual DbSet<State1> State1 { get; set; }
        public virtual DbSet<Status1> Status1 { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
